--- Makefile	2019-08-06 11:20:40.000000000 -0400
+++ Makefile.new	2019-08-15 10:27:46.000000000 -0400
@@ -487,14 +487,6 @@
 OPTIONS_CFLAGS += -DCONFIG_REGPARM=3
 endif
 
-ifneq ($(USE_DL),)
-OPTIONS_LDFLAGS += -ldl
-endif
-
-ifneq ($(USE_THREAD),)
-OPTIONS_LDFLAGS += -lpthread
-endif
-
 ifneq ($(USE_RT),)
 OPTIONS_LDFLAGS += -lrt
 endif
@@ -513,6 +505,14 @@
 OPTIONS_OBJS  += src/ssl_sock.o
 endif
 
+ifneq ($(USE_DL),)
+OPTIONS_LDFLAGS += -ldl
+endif
+
+ifneq ($(USE_THREAD),)
+OPTIONS_LDFLAGS += -lpthread
+endif
+
 # The private cache option affect the way the shctx is built
 ifeq ($(USE_PRIVATE_CACHE),)
 ifneq ($(USE_PTHREAD_PSHARED),)
